Add mock LLM for test purposes; Enable multiple `step()` calls in test units to enhance test robustness
camel-ai/camel pull request #1128
Opened 2024-10-28 04:34 UTC by lllllyh01

## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
`close #364 ` `close #1047 `

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2024-10-30 06:17 UTC, WHALEEYE requested changes
Thanks @lllllyh01, but I think there are some changes needed to be made:
1. we already have a model named `StubModel`, which is also used as a dummy model for testing.
2. In the future we want to replace the `StubModel` with mock because containing test codes in delivered codebase will cause confusion and is not a good practice. We think it's better to keep dummies inside the test module. Here is an existing example using mock for backend models, FYR: https://github.com/camel-ai/crab/blob/main/test/agents/backend_models/test_openai_model.py
3. For multiple step tests, I think one important goal is to make sure the state of `ChatAgent` is not changed unexpectedly (implicitly) after calling each `step()`, i.e. `step()` should have no side effects on the agent and model, especially the configurations. Therefore, I think the test case should be more focused on this part, while the response content is actually not important. To be clearer here are some bugs related to this we found before: #1044 #894 

I know this issue could be tricky to fix, please feel free to reach out if you get stuck or want to have further discussions :)

2024-11-01 01:56 UTC, lllllyh01 commented
> Thanks @lllllyh01, but I think there are some changes needed to be made:
> 
> 1. we already have a model named `StubModel`, which is also used as a dummy model for testing.
> 2. In the future we want to replace the `StubModel` with mock because containing test codes in delivered codebase will cause confusion and is not a good practice. We think it's better to keep dummies inside the test module. Here is an existing example using mock for backend models, FYR: https://github.com/camel-ai/crab/blob/main/test/agents/backend_models/test_openai_model.py
> 3. For multiple step tests, I think one important goal is to make sure the state of `ChatAgent` is not changed unexpectedly (implicitly) after calling each `step()`, i.e. `step()` should have no side effects on the agent and model, especially the configurations. Therefore, I think the test case should be more focused on this part, while the response content is actually not important. To be clearer here are some bugs related to this we found before: [[BUG] O1 Preview Model Will Raise `KeyError` #1044](https://github.com/camel-ai/camel/issues/1044) [[BUG] Tools will be invalid after calling `step()` with output schema #894](https://github.com/camel-ai/camel/issues/894)
> 
> I know this issue could be tricky to fix, please feel free to reach out if you get stuck or want to have further discussions :)

Got it, I'll modify this pr accordingly. Thank you for your further explanation!

2024-11-04 23:18 UTC, lightaime reviewed
Thanks @lllllyh01! Should we refactor `StubModel` for this since they are used for the same propose?

2024-11-04 23:41 UTC, lllllyh01 commented
> Thanks @lllllyh01! Should we refactor `StubModel` for this since they are used for the same propose?

Hi @lightaime , thank you for your comment! Yes I think we can integrate the `FakeLLMModel` into `StubModel`. I will refactor it. I'm also trying to use `Mock()` instead of stub model according to @WHALEEYE suggestions.

This pr is still working in progress and may need some more time to be ready, but please let me know if there are any further comments or suggestions.

2024-11-30 19:44 UTC, Wendong-Fan commented on camel/models/fake_llm_model.py
Thanks @lllllyh01 ! We have `StubModel` and `StubTokenCounter` used for unit tests, maybe we don't need to define new one, but we could polish these two Stub Class based on your work

2024-12-15 09:56 UTC, Wendong-Fan approved these changes
Thanks @lllllyh01 !LGTM

2024-12-16 04:54 UTC, merged