Openai structured
camel-ai/camel pull request #1198
Opened 2024-11-20 15:02 UTC by Wendong-Fan

## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2024-11-20 15:45 UTC, CaelumF requested changes

2024-11-20 15:45 UTC, CaelumF commented on camel/models/openai_model.py
> +                del self.model_config_dict[key]
```suggestion
                del self.model_config_dict["stream"]
```

2024-11-20 15:45 UTC, CaelumF commented on camel/models/openai_model.py
> +        choice = dict(
```suggestion
        # TODO: Handle n > 1 or warn consumers it's not supported
        choice = dict(
```

2024-11-20 15:55 UTC, merged

2024-11-21 18:01 UTC, lightaime reviewed
"When using the SDK, you can use the parsed attribute to access the parsed JSON response as an object. This object will be of the type you defined in the response_format parameter."

```
math_response = completion.choices[0].message.parsed
print(math_response.steps)
print(math_response.final_answer)
```

This feature is very good.Any plan to add it? Maybe we should like to into:

https://github.com/openai/openai-python

to see how it is implemented

2024-11-21 18:05 UTC, lightaime commented
https://platform.openai.com/docs/guides/structured-outputs