update on auto role assignment agent with description
camel-ai/camel pull request #237
Opened 2023-08-01 05:27 UTC by ZhangT-tech

## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2023-08-01 10:01 UTC, Obs01ete requested changes

2023-08-01 10:01 UTC, Obs01ete commented on examples/ai_society/role_playing_with_description.py
> +def main() -> None:
Add tests to your examples.

2023-08-01 10:01 UTC, Obs01ete commented on camel/agents/chat_agent.py
> +import openai
Chat agent should not depend on openai. This is a violation of the dependency inversion principle.

2023-11-13 20:22 UTC, lightaime commented
Hi @ZhangT-tech. Should we close this PR since the `RoleAssignmentAgent` was merged in a seperate PR?

2024-01-13 18:28 UTC, closed without merging