Generate the roles and role description
camel-ai/camel pull request #247
Opened 2023-08-13 19:24 UTC by Appointat

## Description

**Note**: Due to GitHub's security constraints, secret keys are inaccessible in CI/CD workflows for PRs raised from the [fork](https://github.com/Appointat/camel/tree/Role-Generation). This is to safeguard sensitive information. To address this and ensure the workflows run correctly, I created a new [branch](https://github.com/camel-ai/camel/tree/feature/role-generation), "feature/role-generation", directly under the original project and raised this PR from there. The previous [PR #240](https://github.com/camel-ai/camel/pull/240) from the fork will be **closed** to avoid confusion.

Describe your changes in detail.

## Motivation and Context

- [x] I have raised an issue to propose this change ([Feature Request](https://github.com/camel-ai/camel/issues/239 for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [x] Example (update in the folder of example)

## Implemented Tasks

- [ ] Subtask 1
- [x] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.

## Output of the new example
``` shell
AI Assistant sys message:
BaseMessage(role_name='Software Engineer', role_type=<RoleType.ASSISTANT: 'assistant'>, meta_dict={'task': 'Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.', 'assistant_role': 'Software Engineer', 'user_role': 'Financial Analyst', 'assistant_description': "Designing, developing, and testing software for the trading bot; creating algorithms and data structures to optimize the bot's performance; troubleshooting and debugging the bot; monitoring the bot's performance and making adjustments as needed.", 'user_description': "Analyzing financial data and market trends; researching and forecasting stock prices; developing strategies for the trading bot; monitoring the bot's performance and making adjustments as needed."}, content="===== ROLES WITH DESCRIPTION =====\nFinancial Analyst and Software Engineer are collaborating to complete a task: Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.\nFinancial Analyst's competencies, professional characteristics, duties and workflows to complete the task: Analyzing financial data and market trends; researching and forecasting stock prices; developing strategies for the trading bot; monitoring the bot's performance and making adjustments as needed.\nSoftware Engineer's competencies, professional characteristics, duties and workflows to complete the task: Designing, developing, and testing software for the trading bot; creating algorithms and data structures to optimize the bot's performance; troubleshooting and debugging the bot; monitoring the bot's performance and making adjustments as needed.\n===== RULES OF ASSISTANT =====\nNever forget you are a Software Engineer and I am a Financial Analyst. Never flip roles! Never instruct me!\nWe share a common interest in collaborating to successfully complete a task.\nYou must help me to complete the task.\nHere is the task: Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.. Never forget our task!\nI must instruct you based on your expertise and my needs to complete the task.\n\nI must give you one instruction at a time.\nYou must write a specific solution that appropriately solves the requested instruction and explain your solutions.\nYou must decline my instruction honestly if you cannot perform the instruction due to physical, moral, legal reasons or your capability and explain the reasons.\nUnless I say the task is completed, you should always start with:\n\nSolution: <YOUR_SOLUTION>\n\n<YOUR_SOLUTION> should be very specific, include detailed explanations and provide preferable detailed implementations and examples and lists for task-solving.\nAlways end <YOUR_SOLUTION> with: Next request.")

AI User sys message:
BaseMessage(role_name='Financial Analyst', role_type=<RoleType.USER: 'user'>, meta_dict={'task': 'Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.', 'assistant_role': 'Software Engineer', 'user_role': 'Financial Analyst', 'assistant_description': "Designing, developing, and testing software for the trading bot; creating algorithms and data structures to optimize the bot's performance; troubleshooting and debugging the bot; monitoring the bot's performance and making adjustments as needed.", 'user_description': "Analyzing financial data and market trends; researching and forecasting stock prices; developing strategies for the trading bot; monitoring the bot's performance and making adjustments as needed."}, content='===== ROLES WITH DESCRIPTION =====\nFinancial Analyst and Software Engineer are collaborating to complete a task: Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.\nFinancial Analyst\'s competencies, professional characteristics, duties and workflows to complete the task: Analyzing financial data and market trends; researching and forecasting stock prices; developing strategies for the trading bot; monitoring the bot\'s performance and making adjustments as needed.\nSoftware Engineer\'s competencies, professional characteristics, duties and workflows to complete the task: Designing, developing, and testing software for the trading bot; creating algorithms and data structures to optimize the bot\'s performance; troubleshooting and debugging the bot; monitoring the bot\'s performance and making adjustments as needed.\n===== RULES OF USER =====\nNever forget you are a Financial Analyst and I am a Software Engineer. Never flip roles! You will always instruct me.\nWe share a common interest in collaborating to successfully complete a task.\nI must help you to complete the task.\nHere is the task: Develop a highly efficient and self-learning trading bot that incorporates sentiment analysis algorithms to analyze social media trends in real-time, enabling Financial Analyst to make data-driven decisions in volatile market conditions, and integrate it seamlessly into the existing trading platform.. Never forget our task!\nYou must instruct me based on my expertise and your needs to s [...]

2023-08-14 13:33 UTC, Obs01ete requested changes
Thanks for the feature. Let's polish it and have good code coverage.

2023-08-14 13:33 UTC, Obs01ete commented on camel/societies/role_playing.py
> +            if (assistant_description is not None
What if assistant_description is not None and user_description is None?

2023-08-14 13:33 UTC, Obs01ete commented on examples/test/test_ai_society_example.py
> +            ModelType.GPT_3_5_TURBO)
Make it with STUB only.

2023-08-14 13:33 UTC, Obs01ete commented on camel/generators.py
> +        with_role_description (bool, optional): Whether to include the role
Test SystemMessageGenerator in both modes: without and with the role description.

2023-08-14 13:33 UTC, Obs01ete commented on camel/prompts/prompt_templates.py
> +            if (with_role_description):
Remove brackets

2023-08-14 13:33 UTC, Obs01ete commented on camel/societies/role_playing.py
> +             assistant_role_name=assistant_role_name,
Remove `key=` from positional arguments.

2023-08-15 22:07 UTC, Obs01ete requested changes

2023-08-15 22:07 UTC, Obs01ete commented on camel/societies/role_playing.py
> +            if (assistant_description is not None
This logic is getting out of control. Can we make a bird eye view on this and understand do we really mean that much complexity that results in such a bulky code?

2023-08-15 22:07 UTC, Obs01ete commented on examples/test/test_ai_society_example.py
> +def test_role_playing_with_role_generation_example():
Why again having this white crow non-stub test?

2023-08-18 03:18 UTC, lightaime reviewed
Thanks for the PR! I think all the `with_role_description` flags should be removed and just create new `ASSISTANT_PROMPT` and `USER_PROMPT` prompts with role_description in it.

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +            (default: :obj: 'ModelType.GPT_3_5_TURBO')
```suggestion
        model (ModelType, optional): The type of model to use for the agent.
            (default: :obj:`ModelType.GPT_3_5_TURBO`)
```

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +            (default: :obj: 'None')
```suggestion
        model_config (Any, optional): The configuration for the model.
            (default: :obj:`None`)
```

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +            'Given this task, "{task}", generate two role names, ' +
?

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +        num_roles: Optional[int] = 2,
```suggestion
        num_roles: int = 2,
```

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +        Generate role names based on the input task prompt.
```suggestion
        r"""Generate role names based on the input task prompt.
```

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +            num_roles (int): The number of roles to generate.
```suggestion
            num_roles (int, optional): The number of roles to generate.
```

2023-08-18 03:18 UTC, lightaime commented on camel/agents/role_assignment.py
> +                for the task based on which the roles are to be generated.
I guess the `task_prompt` is required. Should we put it as a positional argument?

2023-08-18 03:18 UTC, lightaime commented on camel/prompts/ai_society.py
Prefer to create a new file for this PR and compose it with the prompts from `ai_society.py`. An example can be found in `misalignment.py`. Prefer to remove all the `with_role_description ` flags and create a new `ASSISTANT_PROMPT` and `USER_PROMPT` with `ROLE_DESCRIPTION_PROMPT` in it.

2023-08-30 23:36 UTC, lightaime reviewed
Thanks, @Appointat. This is very cool. Left some comments. Let me know if there is any question!

2023-08-30 23:36 UTC, lightaime commented on examples/role_description/role_playing_with_role_description.py
> +        extend_sys_msg_meta_dicts=sys_msg_meta_dicts,
```suggestion
        assistant_role_name=ai_assistant_role,
        user_role_name=ai_user_role,
        task_prompt=task_prompt,
        task_type=TaskType.ROLE_DESCRIPTION,  # important for role description
        with_task_specify=True,
        task_specify_agent_kwargs=dict(model=model_type),
        extend_sys_msg_meta_dicts=sys_msg_meta_dicts,
```

2023-08-30 23:36 UTC, lightaime commented on examples/test/test_role_description.py
> +            ModelType.GPT_3_5_TURBO)
Testing these two examples with `ModelType.GPT_3_5_TURBO` is too slow and expensive. Should we just patch the return and test them with `ModelType.STUB`?

2023-08-30 23:36 UTC, lightaime commented on camel/societies/role_playing.py
> +                TaskType.MISALIGNMENT,
```suggestion
                TaskType.MISALIGNMENT,
                TaskType.ROLE_DESCRIPTION,
```

2023-08-30 23:36 UTC, lightaime commented on examples/role_description/role_playing_with_role_description.py
> +    ai_user_role = role_names[AI_USER_ROLE_INDEX]
How do we know which is the assistant role and which is the user role?

2023-08-30 23:36 UTC, lightaime commented on camel/agents/role_assignment_agent.py
We may want to add a test for the agent.

2023-08-30 23:36 UTC, lightaime commented on camel/prompts/role_description_prompt_template.py
We may want to add a test for the prompt like https://github.com/camel-ai/camel/blob/master/test/prompts/test_ai_society.py.

2023-09-08 23:56 UTC, lightaime commented
Thanks @Appointat @ZhangT-tech for adding this awesome future!!

2023-09-09 00:00 UTC, merged