update weather function API by using pyowm
camel-ai/camel pull request #334
Opened 2023-10-29 14:19 UTC by yiyiyi0817

## Description

This PR introduces a new API function, and a set of test cases to validate its functionality.              This feature enhancement enhances the CAMEL project by providing access to current weather data based on city name.
This update integrates features related to the OpenWeatherMap API, enabling new weather-related functionality. It is a new edition of #328 .

In order to use these new features, an API key from OpenWeatherMap is required.       Contributors and users who want to run this code will need to:

1. Obtain an API key from OpenWeatherMap by signing up at https://openweathermap.org/api（free API is enough to this function）.
2. Once you have the key, it should be stored securely in the environment variables as 'OPENWEATHERMAP_API_KEY'.       This is critical to ensure the security and privacy of your API key.  Please do not hardcode the key into your codebase.

Please ensure the 'OPENWEATHER_API_KEY' is correctly configured in the environment before running the application.       Incorrect handling of the API key may lead to errors or unexpected behavior.

Thank you for your attention to this requirement as we integrate these exciting new weather features.

## Motivation and Context

**Motivation:**
Weather data is a valuable resource for a wide range of applications, from optimizing energy consumption to improving travel safety.           Users of the CAMEL project have expressed the need for a reliable and easy-to-use way to access current weather information based on geographical coordinates.           This addition of the 'get_current_weather', 'get_current_wind', 'get_current_visibility_distance', 'get_sunrise_sunset' API fulfills that need, providing real-time weather data to CAMEL users, enhancing their experience, and enabling new possibilities for data analysis.

**Context:**
Prior to this change, users had to rely on external services or implement custom solutions to obtain weather data.           The `fetch_current_weather` API simplifies this process, making it more accessible and integrated within the CAMEL framework.           This addition aligns with our project's goal of providing comprehensive and user-friendly AI capabilities.           It leverages the OpenWeatherMap API to retrieve accurate and up-to-date weather information, which complements the existing functionality of CAMEL.

An issue has been raised to propose this change (https://github.com/camel-ai/camel/issues/57)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [x] Example (update in the folder of example)

## Implemented Tasks

- [x] Current Weather(Temperature and weather status)
- [x] Current Wind(speed and direction)
- [x] Current Visibility Distance
- [x] Sunrise&Sunset Time
- [ ] Air Pollution
- [ ] Weather Forecast(need to subscribe plan "One Call by Call" and pay for it)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask.              We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide.              (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly.              (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2023-10-30 15:04 UTC, dandansamax requested changes
Excellent code! The tests coverage is high enough. Leave some tiny suggestions.

2023-10-30 15:47 UTC, yiyiyi0817 commented on pyproject.toml
> +    "pyowm",
Alright, I was indeed a bit uncertain when adding 'pyown' to the 'hugginface-agent' in the toml file. My intention was to consider 'pyown' and 'wikipedia' as parallel functionalities within 'camel,' as I noticed 'wikipedia' being a part of the 'hugginface-agent.

2023-10-30 15:47 UTC, yiyiyi0817 commented on examples/function_call/role_playing_with_function.py
> +                   "KUAST today. What time should we go?")
I also think creating a new role_playing_with_function example might be better. However, due to limitations with my `OPEN_AI_KEY`, I wasn't able to successfully run this code after making changes, so I didn't encounter this ERROR. Additionally, I just found out that 'pyowm' can access the weather for 'Jeddah, Saudi Arabia,' but not for smaller areas like 'Thuwal.' Perhaps we should find a way to inform the LLM about what level of region to pass to this API. I'd like to revert the old example to its original state for now and add a new example later, once the other changes are in place.

2023-10-30 15:47 UTC, yiyiyi0817 commented on camel/functions/weather_functions.py
> +    # Get OPENWEATHERMAP_API_KEY here: https://openweathermap.org/
OK. I agree.

2023-10-30 15:56 UTC, dandansamax commented on pyproject.toml
> +    "pyowm",
No worries. I will add a new PR to fix it after merging this.

2023-10-30 16:01 UTC, dandansamax commented on examples/function_call/role_playing_with_function.py
> +                   "KUAST today. What time should we go?")
About the OpenAI key, you may reach out to @lightaime to find some help.

2023-10-30 16:02 UTC, dandansamax commented
Hi @yiyiyi0817. Sorry, I cannot see your updates. Did you push the changes?

2023-10-30 16:10 UTC, yiyiyi0817 commented on examples/function_call/role_playing_with_function.py
> +                   "KUAST today. What time should we go?")
OK, Thank you. 😃

2023-10-30 16:11 UTC, yiyiyi0817 commented
> Hi @yiyiyi0817. Sorry, I cannot see your updates. Did you push the changes?

Sorry if my previous response was unclear. What I meant is that I will push my updates later.

2023-10-31 07:03 UTC, yiyiyi0817 commented
Hello@dandansamax, I have pushed my updates and would appreciate it if you could review them and consider merging them into the master branch. Thank you!

2023-10-31 09:54 UTC, dandansamax commented on camel/functions/weather_functions.py
> +        return {
Hi @yiyiyi0817. From my perspective, only extracting "Unexpected error occurred while fetching" does not improve the maintainability. We may rather keep it as the old version or exract the whole returned dict.

2023-10-31 11:47 UTC, yiyiyi0817 commented on camel/functions/weather_functions.py
> +        return {
Alright, I have pushed the updated version.

2023-10-31 11:51 UTC, dandansamax approved these changes
LGTM. Please wait @lightaime to have a look.

2023-11-02 13:46 UTC, lightaime commented
Thanks @yiyiyi0817! It looks awesome. Some small comments:

- I am thinking should we merge all functions into one? Because all of them are just a call to `mgr.weather_at_place`.
- Also, It could be great to just return a `str` typed content which is more friendly for LLMs. 
- It would be great to have an example with function calling. Like: https://github.com/camel-ai/camel/blob/master/examples/function_call/role_playing_with_function.py. We can change the task to 
`"Assuming the current year is 2023, estimate KAUST's current age and then add 10 more years to this age, and get the current weather of the city where KAUST is located."`

2023-11-03 05:56 UTC, yiyiyi0817 commented
> Thanks @yiyiyi0817! It looks awesome. Some small comments:
> 
> * I am thinking should we merge all functions into one? Because all of them are just a call to `mgr.weather_at_place`.
> * Also, It could be great to just return a `str` typed content which is more friendly for LLMs.
> * It would be great to have an example with function calling. Like: https://github.com/camel-ai/camel/blob/master/examples/function_call/role_playing_with_function.py. We can change the task to
>   `"Assuming the current year is 2023, estimate KAUST's current age and then add 10 more years to this age, and get the current weather of the city where KAUST is located."`

Hi Guohao@lightaime, Thank you for your suggestion.  

I will convert the output to a string type and include the enhancement in role_playing_with_function.py to add "and get the current weather of the city where KAUST is located."

I've separated the weather module into four distinct functions because the required units for temperature, wind, visibility distance, and sunrise/sunset are different, potentially leading to a function with numerous parameters.  Moreover, there might be instances where the LLM would only need information on one of those aspects at a time, not all together.

Hence, I'm contemplating whether combining them would indeed streamline the process or if it's more practical to maintain them as separate functions to cater to specific needs efficiently.  I’m open to further discussion on this matter if needed.

2023-11-05 07:04 UTC, lightaime commented
Hi @yiyiyi0817. Thanks for your explanation. It makes sense to separate them since the units. However, it will also increase the difficulty for function calling because more functions need to be considered in the function calling process. How about we introduce temp_units, wind_units, ... and combine them into a single function? WDYT?

2023-11-05 09:05 UTC, yiyiyi0817 commented
> Hi @yiyiyi0817. Thanks for your explanation. It makes sense to separate them since the units. However, it will also increase the difficulty for function calling because more functions need to be considered in the function calling process. How about we introduce temp_units, wind_units, ... and combine them into a single function? WDYT?

Given the convenience it brings to function calling, I agree with the proposal to merge these functions into one. I'll push the updated version soon. Thank you for the feedback! @lightaime

2023-11-05 09:47 UTC, dandansamax commented
Hi. Sorry to modify your code. But I added the `OPENWEATHERMAP_API_KEY` to the github workflow so that pytest doesn't fail.

2023-11-06 10:49 UTC, yiyiyi0817 commented
Hello, I have submitted new code and look forward to your review and merging. @lightaime @dandansamax

2023-11-06 15:25 UTC, lightaime reviewed
Thanks @yiyiyi0817. It looks great!! Just some last picky comments.

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +                         https://openweathermap.org/")
```suggestion
        raise ValueError("`OPENWEATHERMAP_API_KEY` not found in environment \
                          variables. Get `OPENWEATHERMAP_API_KEY` here: \
                         `https://openweathermap.org`.")
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +    Retrieve the OpenWeatherMap API key from environment variables.
We usually use `r-string` for docstrings.
```suggestion
    r"""Retrieve the OpenWeatherMap API key from environment variables.
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +    # Get OPENWEATHERMAP_API_KEY here: https://openweathermap.org/
```suggestion
    # Get `OPENWEATHERMAP_API_KEY` here: https://openweathermap.org
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +    wind details, visibility, and sunrise/sunset times, all formatted as \
```suggestion
    r"""Fetch and return a comprehensive weather report for a given city as a
    string. The report includes current weather conditions, temperature,
    wind details, visibility, and sunrise/sunset times, all formatted as
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +                          'unix', 'iso', 'date'. Default is 'unix'.
The indentation of the docstring is a bit weird here. We use 4 spaces for indentation usually.

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +                          'celsius', 'fahrenheit'. Default is 'kelvin'.
For default values, we use the following format. A reference of docstring can be found in the [`ChatAgent`](https://github.com/camel-ai/camel/blob/master/camel/agents/chat_agent.py)
```suggestion
                          'celsius', 'fahrenheit'. (default: :obj:`kelvin`)
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +        "Weather in Paris, FR: 15°C, feels like 13°C. Max temp: 17°C, Min temp\
```suggestion
        "Weather in Paris, FR: 15°C, feels like 13°C. Max temp: 17°C, Min temp
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +        Please ensure that the API key is valid and has permissions to access \
```suggestion
        Please ensure that the API key is valid and has permissions to access
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +            else str(observation.weather.visibility(unit='miles'))
Let's use brackets to format:
```suggestion
        visibility = (str(visibility_distance) if visibility_units == 'meters'
            else str(observation.weather.visibility(unit='miles')))
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +            f"Sunrise at {sunrise_time}, Sunset at {sunset_time}.")
```suggestion
            f"Weather in {city}: {temperature['temp']}°{temp_units.title()}, "
            f"feels like {temperature['feels_like']}°{temp_units.title()}. "
            f"Max temp: {temperature['temp_max']}°{temp_units.title()}, "
            f"Min temp: {temperature['temp_min']}°{temp_units.title()}. "
            f"Wind: {wind_speed} {wind_units} at {wind_deg} degrees. "
            f"Visibility: {visibility} {visibility_units}. "
            f"Sunrise at {sunrise_time}, Sunset at {sunset_time}.")
```

2023-11-06 15:25 UTC, lightaime commented on camel/functions/weather_functions.py
> +            {city}: {str(e)}"
```suggestion
        error_message = (f"An error occurred while fetching weather data for {city}: {str(e)}")
```

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +            f"Temperature {temp} not in range for {temp_units}"
Same here. Can we use brackets instead of back slash for formatting?

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +            f"Wind speed {wind_speed} not in range for {wind_units}"
Same here. Can we use brackets instead of back slash for formatting?

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +            f"Visibility {visibility} not in range for {visibility_units}"
Same here. Can we use brackets instead of back slash for formatting?

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +            format is missing from the report."
Same here. Can we use brackets instead of back slash for formatting?

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +            sunset time in the report."
Same here. Can we use brackets instead of a back slash for formatting?

2023-11-06 15:25 UTC, lightaime commented on test/functions/test_weather_function.py
> +def test_temperature(api_key):
We can also do all the 4 tests in one function. What do you think?

2023-11-06 15:25 UTC, lightaime commented on examples/function_call/role_playing_with_function.py
Let's add `WEATHER_FUNCS` to the `function_list` and test it.

2023-11-09 15:07 UTC, yiyiyi0817 commented
> Thanks @yiyiyi0817. It looks great!! Just some last picky comments.

Hello Guohao@lightaime, I’ve updated my code format based on the previous suggestions and pushed the new version. If there are still any other details that need attention, please let me know. Thank you!

2023-11-09 19:10 UTC, lightaime commented
Thanks @yiyiyi0817!!

2023-11-09 19:12 UTC, merged